### PR TITLE
fixed the comments

### LINKED ISSUE #4: Comments are unhelpful and do not help understand code

### PR DESCRIPTION
**Pull request by annagrigoryan7**

### CODE REVIEW

**Review by jordanbruce44 — APPROVED** [review]
LGTM

**Review by mghazlett — APPROVED** [review]
LGTM/ **Are these comments are only on the test functions or am I not seeing everything?** 

I think we may need to continue adding comments while we code + do one final sweep to make sure the final code has adequate comments throughout

**Comment by mghazlett** [comment]
> LGTM/ **Are these comments are only on the test functions or am I not seeing everything?**
> 
> I think we may need to continue adding comments while we code + do one final sweep to make sure the final code has adequate comments throughout

I will work on the "gamblers ruin" code comments

**Comment by mghazlett** [comment]
Per Tristan, docstrings should answer _why_ are we doing this, rather than what are we doing (because we can all read the code to figure out the what!)

**Comment by tristntran** [comment]
@mghazlett LMK when you have the rest of the comments done and I'll merge it in

**Pull request closed without merging**
