### PR TITLE
Added period functionality

### LINKED ISSUE #1: Test find nth state is failing
The test nth state function fails here.

### PR DESCRIPTION
**Pull request by ProvenNoIQ**

### CODE REVIEW

**Review by mghazlett — APPROVED** [review]
Looks good to me. Thank you James!

One question about line 71:  win_states = np.arange(start_cash, goal+min_bet, min_bet)
Why are we adding goal+min_bet?

**Comment by katherinehansen1** [comment]
> Looks good to me. Thank you James!
> 
> One question about line 71: win_states = np.arange(start_cash, goal+min_bet, min_bet) Why are we adding goal+min_bet?

I think its because np.arange isn't inclusive, so we need that to actually include the end goal in our array!

**Review by katherinehansen1 — APPROVED** [review]
Looks good to me!

**Review by annagrigoryan7 — APPROVED** [review]
Looks good!

**Pull request merged**
